export const CropsData = [
  {
    name: "WHEAT",
    imageURL:
      "https://d2xsikgwxkxyoe.cloudfront.net/media/25728/wheat-variety.jpg",
    data: "Wheat is grown on 13 percent of the cropped area of India. Next to rice, wheat is the most important food-grain of India and is the staple food of millions of Indians, particularly in the northern and north-western parts of the country.\nIt is rich in proteins, vitamins and carbohydrates and provides balanced food. India is the fourth largest producer of wheat in the world after Russia, the USA and China and accounts for 8.7% of the world’s total production of wheat.\n\nSuitable factors required for the cultivation of Wheat are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nThe best wheat are produced in areas favoured with cool, moist weather during the major portion of the growing period followed by dry, warm weather to enable the grain to ripen properly. The optimum temperature range for ideal germination of wheat seed is 20-25°C though the seeds can germinate in the temperature range 3.5 to 35°C.\n\n2. Rainfall:\nMaximum rainfall required for wheat is 75cm and minimum of 20-25cm is needed.\n\n3. Soils:\nWheat is grown in a variety of soils of India. Soils with a clay loam or loam texture, good structure and moderate water holding capacity are ideal for wheat cultivation. Care should be taken to avoid very porous and excessively drained oils. Soil should be neutral in its reaction. Heavy soil with good drainage are suitable for wheat cultivation under dry conditions. These soils absorb and retain rain water well. Heavy soils with poor structure and poor drainage are not suitable as wheat is sensitive to water logging. Wheat can be successfully grown on lighter soils provided their water and nutrient holding capacity are improved.\n\n4. Fertilizers: The time and placement of fertilizer is another area where significant progress was made. It was demonstrated that 120 kg nitrogen, 60 kg phosphorus and 30 kg potash per hectare were required for optimum productivity. The N was to be applied in two split doses of 60 kg as basal and the remaining 60 kg at first irrigation and full phosphorus and potash to be applied as basal.",
  },
  {
    name: "BAJRA",
    imageURL:
      "https://p0.pikrepo.com/preview/58/316/green-cactus-plants-under-blue-sky-during-daytime.jpg",
    data: "Bajra or pearl millets is grown for grain as well as for fodder purpose whereas Napier or elephant grass is mainly cultivated as forage crop. Napier-bajra is hybridization between bajra and elephant grass. This hybrid increases number of tillers thus yield, quality of forage also minimize risk of becoming weed in case of napier. After plantation, it give yield continuously upto 2-3 years.\n\nSuitable factors required for the cultivation of Bajra are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nBajra grows well in dry and warm climate conditions.Ideal temperature for bajra cultivation is between 20°C to 30°C.\n\n2. Rainfall:\nIt requires low annual rainfall ranging between 40-50 cm and dry weather. The crop may tolerate drought but cannot withstand high rainfall of 90 cm or above.\n\n3. Soils:\nBajra can be grown in wider range of soil. However, It thrives best in black cotton soil, sandy loam soil having well drainage. This crop dose not prefer acidic and water logging soil. Avoid saturated soil for its cultivation. It grows successfully well in soil with low pH. Bajra can be easily grown in region where other crops like wheat and maize would not survive.\n\n4. Fertilizers:\nAmount of fertiliser should be given on the basis of soil test value for maximum profit. General recommendations based on experimental finding s are 100-120 kg nitrogen, 40-60 kg P2O5 and 30-40 kg K2O per hectare. Half dose of nitrogen and full doses of phosphorus and potassium should be applied at the time of sowing in furrows approximately 3-5 centimetres below the seed.",
  },
  {
    name: "JOWAR",
    imageURL:
      "https://cdn.pixabay.com/photo/2021/02/14/14/09/jowar-6014577_960_720.jpg",
    data: "Jowar is one of the major staple food grain crops in India. Out of the total area under jowar cultivation in India, 50% is cultivated in Maharashtra. Whereas out of the total production of Jowar in the nation, 52% is from Maharashtra. Karnataka, Andhra Pradesh, Tamil Nadu.\nOne more advantage of this crop is that it can be grown in both Kharif and Rabi season. Also, it can handle and grow on a wide range of soil types starting from fertile to less nutrient soils but an effective output largely depends on soil moisture, resistance and porosity.\n\nSuitable factors required for the cultivation of Jowar are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nThe ideal temperature for the growth of jowar is between 27°C - 32°C and the crop cannot be grown below the temperature of 16°C.\n\n2. Rainfall:\nJowar crop requires rainfall about 40 cm annually. Jowar is extreme drought tolerant crop and recommended for dry regions.\n\n3. Soils:\nJowar is grown on a variety of soil types but the clayey loam soil rich in humus is found to be the most ideal soil. It may tolerate mild acidity to mild salinity under pH 5.5 to 8.0. A good jowar soil must have an efficient drainage facilities though, it may withstand water logging more than maize.\n\n4. Fertilizers:\nBefore sowing add 4-6 tons of Farm Yard Manure or well decomposed cow dung in soil. Apply basal dose of N:P:K@20:8:10kg/acre in form of Urea@44kg, SSP@50kg/acre and Potash@16kg/acre. Apply all dose of P and K along with 50% N is applied as basal at the time of sowing. Apply remaining half dose of fertilizer, 30days after sowing.",
  },
  {
    name: "MAIZE",
    imageURL: "https://d2xsikgwxkxyoe.cloudfront.net/media/38287/maize.png",
    data: "Maize, also known as corn in the US, Canada & Australia is the most widely produced crop all over the world. Maize have carbohydrate(70%) , protein(10%) and oil(4%). All these elements are very important for the human body. Maize is a ripe and high yielding crop in a short time as compared to other crops. If the farmer do farming with a proper guidance and latest technology, then they can earn good profit from the high yield of this crop.\n\nSuitable factors required for the cultivation of Maize are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nMaize is grown in temperatures between 18°C and 27°C during the day and around 14°C during the night. But the most important factor is the 140 frost-free days. The crop is very susceptible to frost; therefore, its cultivation in temperate latitudes is limited.\n\n2. Rainfall:\nMaize is grown mostly in regions having annual rainfall between 60 cm to 110 cm. But it is also grown in areas having rainfall of about 40 cm.\n\n3. Soils:\nMaize grows in a wide range of soils, ranging from temperate podzols to the leached red soils of the tropics. But, the best suitable soil for maize is deep, rich soils of the sub-tropics, where there is abundant nitrogen.\n\n4. Fertilizers:\nThe main macro elements commonly required by a plant are Nitrogen (N), Phosphorus (P) and then Potassium (K) but there are a number of other elements such as Magnesium (Mg), Sulphur (S), Calcium (Ca), Zinc (Zn) and Manganese (Mn) that is needed for optimal growth.",
  },
  {
    name: "RICE",
    imageURL:
      "https://i0.wp.com/worldlistmania.com/wp-content/uploads/2021/06/in-rice-field-2679153_640.jpg",
    data: "Rice is the staple crop of India, and every day millions of Indians find comfort in it. With a high carbohydrate content, it is known to provide instant energy, and is a staple that is consumed by the majority of India’s population. Hence, the importance of rice crop in the country can’t be negated.\n\nSuitable factors required for the cultivation of Rice are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nRice is a tropical crop and grown where the average temperature during the growing season is between 20°C and 27°C.\nAbundant sunshine is essential during its four months of growth. The minimum temperature should not go below 15°C as germination cannot take place below that temperature.\n\n2. Rainfall:\nPaddy requires more water than any other crop. As a result, paddy cultivation is done only in those areas where minimum rainfall is 115 cm. Although the regions are having average annual rainfall between 175—300 cm are the most suitable.\nPaddy also needs flooded conditions with the depth of water varying over 25 mm at the time of transplanting to as much as 150 mm for 10 weeks of the growing period.\n\n3. Soils:\nPaddy is grown in wide range of soil, from the podzolic alluvium of China to the impermeable heavy clay of central Thailand. Fertile riverine alluvial soil is best for rice cultivation.\nClayey loam soil in monsoon land is considered to be the best for rice cultivation as water retention capacity of this soil is very high. Rice is also grown in saline areas of deltic region. Rice cultivation needs high fertilizer appli­cation.\n\n4. Fertilizers:\nPaddy requires three essential plant nutrients: nitrogen, phosphorus and potassium. Most paddy lands have a moderate quantity of such nutrients, but if they are deficient, organic manure or artificial fertilizers have to be used.",
  },
  {
    name: "SUGARCANE",
    imageUrl:
      "https://growise.000webhostapp.com/images/sugarcane.jpeg",
    data: "Sugarcane is the main source of sugar, jaggery and khandsari. About two-thirds of the total sugarcane produced in India is consumed for making jaggery and khandsari and only one third of it goes to sugar factories. It also provides raw material for manufacturing alcohol. In India, Maharashtra is largest producer of sugar and it contributes about 34% of sugar in country followed by Uttar Pradesh.\n\nSuitable factors required for the cultivation of Sugarcane are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nSugarcane plants are grown for 10 months in the greenhouse at 27°C, considered the optimal temperature, and at low temperature (15°C) and high temperature (45°C).\n\n2. Rainfall:\nSugar cane crops require a minimum of 150 cm of rainfall to be grown.\n\n3. Soils:\nWell drained, deep, loamy soil with ground water table below 1.5-2 m from the soil surface with adequate water holding capacity is ideal for sugarcane cultivation. It can tolerate considerable degree of acidity and alkalinity so it can be grown on soil, ranging from 5 to 8.5. If soil is low in pH (less than 5) add lime in soil and for high pH (more than 9.5) do gypsum application.\n\n4. Fertilizers:\nBefore sowing at time of last ploughing, add well decomposed cow dung@8ton or Vermicompost+ Ralligold@8-10kg or PSB@5-10kg per Acre. At time of sowing apply Urea@66kg per acre. At development stage, apply second dose of Urea@66kg at the time of second irrigation. Apply third dose of Urea@66kg at time of fourth irrigation.\nIn winter due to low temperature uptake of nutrient by crop become less and plant give yellow appearance. To recovered crop take spray of 19:19:19@100gm/15Ltr of water. In water scarcity situation spray of Urea+Potash@2.5kg/100Ltr is helpful for crop.",
  },
  {
    name: "POTATO",
    imageUrl:
      "https://thumbs.dreamstime.com/b/potato-plant-outside-soil-raw-potatoes-young-potato-plant-outside-soil-lot-raw-potatoes-190781501.jpg",
    data: "Potato is most important food crop of the world. It is economical crop. It is rich source of starch and vitamin. It is used as vegetable also used for making of chips. It is used for several industrial purposes for production of starch and alcohol. Potato is grown almost in all states. Uttar Pradesh, West Bengal, Punjab, Karnataka, Assam and Madhya Pradesh are major potato growing states.\n\nSuitable factors required for the cultivation of Potato are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nPotato is a temperate climate crop, however it grows under a diverse range of climatic conditions. The vegetative growth of the plant is best at a temperature of 24°C while tuber development is favoured at 20°C. Hence, potato is grown as a summer crop in the hills and as a winter crop in the tropical and subtropical regions.\n2. Rainfall:\nPotato is mostly grown as a rainfed crop in regions receiving a rainfall of 1200 – 2000 mm per annum.\n\n3. Soils:\nIt can grow on wide range of soil, ranging from sandy loam, silt loam, loam and clay soils. It gives best yield when grown under well drained sandy loam and medium loam soils with rich in organic content. They can grow in acidic soil. It cannot grow under waterlogged soil also saline, alkaline soils are not suitable for potato cultivation.\n\n4. Fertilizers:\nA fertilizer dose of 180-240 kg N, 60-90 kg P2 O5 and 85- 25 130 K2O per hectare is recommended for alluvial soils of Indo Gangetic plains. In the hill zone, the 2 application of 100-150 kg N, 100-150 kg P2 O5 and 50-100 kg K2O per hectare is recommended. In black soils of plateau areas about 120-150 kg N, 50 kg each of P2 O5 & K2O is recommended. In the acidic soils of southern plateau 120kg N, 115 kg P2 O5 , and 120 K2O kg per hectare are recommended for potato production.",
  },
  {
    name: "COTTON",
    imageUrl:
      "https://media.istockphoto.com/photos/branch-of-ripe-cotton-picture-id589121090?k=20&m=589121090&s=612x612&w=0&h=L42Q3yHBKwJ87lQzeY4MgugSY7meBRVbI0F5Tx7_mU8=",
    data: "Cotton plant is a shrub and is widely cultivated in over 90 countries for its fiber and secondly for seeds. About 2.5% of world cropland is planted with cotton. It is native to Asia and Africa. We sow the seeds during spring, we harvest the cotton during autumn, and then we plow and destroy the plants, so that we can sow again next spring in an empty field.\n\nSuitable factors required for the cultivation of Cotton are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nCotton plant sowing temperature should go maximum till 35°C and go minimum to 25°C.\nIt's Harvesting temperature cango maximum till 25°C and go minimum to 15°C\n\n2. Rainfall:\nCotton crop requires around 55-100 cm of rainfall to be grown.\n\n3. Soils:\nIt can be grown on all type of soil having pH ranges in-between 6 and 8. Deep, friable, well drained and fertile soil are good for crop cultivation. Sandy, saline or water logged soils are not suitable for cotton cultivation. The depth of soil should not be less than 20-25 cm.\n\n4. Fertilizers:\nThe fertilizer dose of 100:50:50 (NPK) kg/ha for irrigated cotton; 80 :40:40 (NPK)kg/ha for rainfed cotton hybrids and 50:25:25 NPK kg/ha both for desi and hirsutum varieties are recommended. Nitrogen should be in two splits for rainfed cotton crop i.e. 50% at sowing time and 50% at square formation stage and three split for irrigated cotton i,e, 1/3rd at sowing time, 1/3rd at one month after sowing and remaining 1/3rd at 60 DAS. While whole P and K should be applied as basal dose for both rainfed and irrigated cotton.",
  },
  {
    name: "CARROT",
    imageUrl:
      "https://growise.000webhostapp.com/cropImages/carrot.jpeg",
    data: "Carrot 'annual' or 'biannual' herb belongs to family of Umbelliferae and it is native of 'Europe'. It is a great source of Vitamin A. Carrot is major vegetable crop of India. Haryana, Andhra Pradesh, Karnataka, Punjab and Uttar Pradesh are major carrot growing states.\n\nSuitable factors required for the cultivation of Carrot are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nThe optimum temperature for its growth is between 16 to 20°C. The temperature lower than 16°C affects the development of colour.\nThe temperatures between 15 to 20°C is better for developing attractive roots with excellent red colour and quality\n\n2. Rainfall:\nCarrot crop requires around 75-100 cm of rainfall to be grown.\n\n3. Soils:\nFor good root development carrot required deep, loose loamy soils. Heavy soils as well as very loose soils are not suitable for carrot cultivation. For optimum yield pH of soil should be in range of 5.5 to 7 (pH of 6.5 is ideal for good yield).\n\n4. Fertilizers:\nAlong with well decomposed cowdung, apply Nitrogen@25kg (in form of Urea@55kg), Phosphorus@12kg (in form of SSP@ 75kg/acre) and Potash@30kg (in form of MOP@50kg) per acre in soil at time of sowing. Potash is required for good development of roots.",
  },
  {
    name: "TEA",
    imageUrl:
      "https://s3.envato.com/files/240113585/tea%20leaves%20with%20blurry%20background.jpg",
    data: "Tea production, cultivation of the tea plant, usually done in large commercial operations. The plant, a species of evergeen (Camellia sinensis), is valued for its young leaves and leaf buds, from which the tea beverage is produced.\n\nSuitable factors required for the cultivation of Tea are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nThe most suitable condition of growing tea is average temperature between 12.5-13°C or more, and in winter time, the temperature do not stay –15°C or less for a long hours.\n\n2. Rainfall:\nThe tea plant requires a minimum rainfall of 1200mm year, but 2500-3000mm year is considered optimum.\n\n3. Soils:\nTea is grown in soils that differ from one country to another, with the most important feature being the soil pH. The pH requirement for the growth of tea is in the range of 4.5-5.6. The optimum soil conditions recommended for tea growth include a well-drained, deep and well-aerated soil with more than 2% organic matter.\n\n4. Fertilizers:\nApply recommended doses of NPK mixture, Zinc sulphate and Magnesium sulphate and also, if necessary, Manganese sulphate and Boric acid, as foliar spray. Most fertilizers, except lime sulphur, are compatible with fungicides and pesticides.",
  },
  {
    name: "CAULIFLOWER",
    imageUrl:
      "https://www.apnikheti.com/upload/crops/1801idea99cauliflower-1.jpg",
    data: "Cauliflower is popular vegetable and this belongs to family Cruciferous. It work as anti-cancer agent. It promotes heart health, lower cholesterol levels. The major cauliflower producing states are Bihar, Uttar Pradesh, Orissa, West Bengal, Assam, Haryana and Maharashtra.\n\nSuitable factors required for the cultivation of Cauliflower are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nThe optimum monthly average temperature ranges from 15 to 20 °C. The early varieties require higher temperatures and longer day length.\n\n2. Rainfall:\nCauliflower crop requires around 120-125mm of rainfall to be grown.\n\n3. Soils:\nIt can grow well in wide range of soil from sandy loam to clay. For late sown variety, clay loam soils are preferred and for early maturing varieties sandy loam soil is recommended. pH of soil should be in range of 6 to 7. Add lime in case of low pH soil.\n\n4. Fertilizers:\nGenerally, the cauliflower crop is required to give 200 kg of Nitrogen, 75 kg of phosphorus and 75 kg potassium per hectare for optimum yield.\nNitrogen 100kg, 75kg phosphorus and 75kg potash should be applied at the time of transplanting. The remaining half of nitrogen should be given 30 and 45 days after transplanting.",
  },
  {
    name: "JUTE",
    imageUrl:
      "https://t3.ftcdn.net/jpg/03/09/09/88/360_F_309098844_is7Ts7lDQ5ZD5E7IXtTzTmoa51LVoi2M.jpg",
    data: "A jute crop is usually harvested when the flowers have been shed but before the plants’ seedpods are fully mature. If jute is cut before then, the fibre is weak; if left until the seed is ripe, the fibre is strong but is coarser and lacks the characteristic lustre.\n\nSuitable factors required for the cultivation of Jute are :\n1. Temperature\n2. Rainfall\n3. Soils\n\n1. Temperature:\nJute plant, which requires a warm humid climate for matured growth, survives between 17°C and 41.5°C.\n\n2. Rainfall:\nIn the ideal situation pre-monsoon rain starts about the middle of March and totals 150 mm to 120 mm spread over 15-20 days. The pre-monsoon is followed by a dry period, which may cover 30 to 40 days. Ideally, light rains at intervals of 10 days or so suit the seedlings growing.\nThe third phase or monsoon should have 1200 to 1500 mm of precipitation distributed over 75 to 80 days.\n\n3. Soils:\nJute can be raised on all kinds of soils from clay to sandy loam, but loamy alluvial are best suited. Laterite and gravel soils are not suitable for this crop. The new grey alluvial soils of good depth, receiving silt from the annual floods are the best for jute cultivation.\n",
  },
  {
    name: "COFFEE",
    imageUrl:
      "https://plantslive.in/wp-content/uploads/2017/10/coffee-plant.jpg",
    data: "The coffee plant grows as a bush or as a tree. Remarkable is the fact, that this tropical plant can carry blossoms and fruits of different degrees of ripeness at the same time. The coffee bean as we know it is the seed of the coffee plant. There are more than 80 coffee types.\n\nSuitable factors required for the cultivation of Coffee are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nCoffee requires an average temperature between 20°-27°C.\n\n2. Rainfall:\nCoffee needs abundant rainfall, i.e., 100 to 200 cm annually. The hill slopes which receive orthographic rainfall are thus best for coffee cultivation.\n\n3. Soils:\nCoffee plants prefer acidic soil, so if your plant is not thriving add organic matter such as sphagnum peat moss to increase soil pH. The ideal pH range is closer to 6 to 6.5.\n\n4. Fertilizers:\nThe coffee plant’s need for zinc, iron, copper, sulfur, manganese, boron, magnesium, sodium and chlorine, is something to keep in mind.",
  },
  {
    name: "RAGI",
    imageUrl:
      "https://t3.ftcdn.net/jpg/03/86/14/32/360_F_386143218_aujSBaM9BEac5yLUfnOWiqzfQ3PkZN90.jpg",
    data: "'Ragi' also known as Finger Millet, is a robust, popular food and marvellous grain crop in India. It is called dry land crops, mostly cultivated by the people of Andhra Pradesh, Karnataka and Tamil Nadu & Kerala, both tropical and sub-tropic regions.\n\nSuitable factors required for the cultivation of Ragi are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nFor best growth, Ragi cultivation requires daytime temperatures of 30 °C to 34 °C and night temperatures of 22°C to 25 °C.\n\n2. Rainfall:\nOptimum rainfall is around 100 cm per year.\n\n3. Soils:\nA broad array of soils, from rich loams to poor low uplands with good organic matter, may be used to cultivate ragi. However, porous/light red loam/sandy loam soils are ideal for agriculture with strong internal drainage. Ragi are best planted in 4.5 to 8.0 pH soils.\n\n4. Fertilizers:\nThe use of fertilisers such as NPK is determined by the region and soil. NPK should be used in different areas depending on the soil fertility.",
  },
  {
    name: "ONION",
    imageUrl:
      "https://d2xsikgwxkxyoe.cloudfront.net/media/25084/growing-organic-onions-e1523106941962.jpg",
    data: "Onions are a cold-season fall or spring crop, easy to grow because of their hardiness.\nOnions can be planted in either the spring or fall. Onion plants grow well in raised beds or raised rows at least 4 inches high. We usually plant a mix of white, yellow, and red onions.\n\nSuitable factors required for the cultivation of Onion are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nThe optimum temperature for vegetative phase and bulb development is 13-24˚C and 16-25˚C, respectively.\n\n2. Rainfall:\nIt requires about 70% relative humidity for good growth. It can grow well in places where the average annual rainfall is 650-750 mm with good distribution during the monsoon period.\n\n3. Soils:\nOnions are easy to grow. They perform best in well-drained, slightly acidic, fertile soils in full sun. Heavy soils can be improved by incorporating organic matter, such as compost, into the soil. Onions require higher fertility levels than most other vegetables.\n\n4. Fertilizers:\nApplication of 15 kg sulphur/ha is sufficient for growing onion crops in soils having sulphur level above 25 kg/ha while 30 kg sulphur/ha is needed for soils having sulphur level below 25 kg/ha for optimum production of onion.",
  },
  {
    name: "SOYBEAN",
    imageUrl:
      "https://rukminim1.flixcart.com/image/416/416/kj7gwi80-0/plant-seed/x/z/i/100-hs272-shop-360-garden-original-imafyt4reuhczmsh.jpeg?q=70",
    data: "Soybean called as golden beans is belongs to legume family. It is native of East Asia. It is a rich source of Protein also excellent source of fibre. Oil extracted from soybean contain small amount of saturated fat. In Punjab, it plays an important role in crop diversification.\n\nSuitable factors required for the cultivation of Soybeans are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nThe optimum temperature for soybean is 20-30˚C, with temperatures of 35˚C and above considered inhibitory to production.\n\n2. Rainfall:\nThe crop requires about 60-65 cm annual rainfall drought at flowering or just before flowering results in flower and pod drops, while rains during maturity impairs the grain quality of soyabean.\n\n3. Soils:\nIt gives good result, when grown on well drained, fertile loamy soils. pH of 6 to 7.5 is favourable for optimum yield of soybean. Water logged, saline/alkaline soils are not suitable for its cultivation. Low temperature affect crop severely.\n\n4. Fertilizers:\nApply FYM or well decomposed cowdung@4 ton/acre. Also apply Nitrogen@12.5 kg and Phosphorus@32 kg in form of Urea@28kg and SSP@200 kg per acre at time of sowing.\nTo obtain good growth and optimum yield, take spray of Urea@3 kg/150 ltr of water on 60th and 75th day after sowing.",
  },
  {
    name: "GROUNDNUT",
    imageUrl:
      "https://media.istockphoto.com/photos/peanut-picture-id532971254?k=20&m=532971254&s=612x612&w=0&h=67Msk_vYO8xlXMU12lcND3VSgSXTmV0cbzhT5361keI=",
    data: "Groundnut is the third most important oilseed of world. In India, it is available throughout the year. It is important source of protein grown mostly under rain-fed conditions. In India, Uttar Pradesh, Madhya Pradesh, Rajasthan, Gujarat, Maharashtra, Karnataka, Andhra Pradesh and Tamil Nadu are major groundnut growing states.\n\nSuitable factors required for the cultivation of GroundNut are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nGroundnut requires about 20˚ C to 25˚C of temperature and needs dry weather during the ripening stage.\n\n2. Rainfall:\nGroundnut needs light to moderate rainfall between 50 to 100cm.\n\n3. Soils:\nGroundnut is raised in a sandy loam as well as well drained sandy clay loam soil. Deep well- drained soil with pH of 6.5 -7 as well as having great fertility are perfect for groundnut cultivation. Heavy and stiff clays are unsuitable for groundnut cultivation as the pod development is hampered in these soils.\n\n4. Fertilizers:\nApply Urea@13kg/acre, SSP@50kg/acre and depending upon soil testing if soil show deficiencies of potash then apply 10kg/acre of MoP. Also apply Gypsum@50kg/acre. Broadcast gypsum and drill all fertilizers at time of sowing. Application of gypsum encourages pod formation and better filling up of the pods.",
  },
  {
    name: "PEAS",
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQItFdJAQgO2beudAmRcV68R-I33pUWxoWDtELiSMyGrumpTFMaalQzIBnE4C3A_-e1NW8&usqp=CAU",
    data: "It belongs to Leguminaceae family. It is a cool season crop grown throughout the world. Green pods are used for vegetable purpose and dried peas are used as pulse. In India it is cultivated in Himachal Pradesh, Madhya Pradesh, Rajasthan, Maharashtra, Punjab, Haryana, Karnataka and Bihar. It is rich source of proteins, amino acids and sugars. Green peas straw is good source of nutritional fodder for livestock.\n\nSuitable factors required for the cultivation of Peas are :\n1. Temperature\n2. Rainfall\n3. Soils\n4. Fertilizers\n\n1. Temperature:\nIdeal temperature for green peas cultivation is between 10˚C to 30˚C. Above 30˚C temperature may result in poor yielding.\n\n2. Rainfall:\nGreen Peas cultivation requires soil moisture content @ flowering and pod development stage. Ideal rainfall of 500 mm required for its crop growth.\n\n3. Soils:\nIt can grow on various soil types from sandy loam to clay soils. It gives best results when grown under well drained soil with pH range of 6 to 7.5. Crop cannot withstand in water logging conditions. For acidic soil, do limming.\n\n4. Fertilizers:\nAt time of sowing apply Nitrogen@20kg in form of Urea@50kg and Phosphorus@25kg in form of Superphosphate@150kg per acre. Drill complete dose of fertilizer along the rows.",
  },
];
