export const states = [
    
{id: 0, label: 'Andaman & Nicobar', value: 'Andaman & Nicobar'},
{id: 1, label: 'Andhra Pradesh', value: 'Andhra Pradesh'},
{id: 2, label: 'Arunachal Pradesh', value: 'Arunachal Pradesh'},
{id: 3, label: 'Assam', value: 'Assam'},
{id: 4, label: 'Bihar', value: 'Bihar'},
{id: 5, label: 'Chandigarh', value: 'Chandigarh'},
{id: 6, label: 'Chhattisgarh', value: 'Chhattisgarh'},
{id: 7, label: 'Dadra & Nagar Haveli', value: 'Dadra & Nagar Haveli'},
{id: 8, label: 'Daman & Diu', value: 'Daman & Diu'},
{id: 9, label: 'Delhi', value: 'Delhi'},
{id: 10, label: 'Goa', value: 'Goa'},
{id: 11, label: 'Gujarat', value: 'Gujarat'},
{id: 12, label: 'Haryana', value: 'Haryana'},
{id: 13, label: 'Himachal Pradesh', value: 'Himachal Pradesh'},
{id: 14, label: 'Jammu & Kashmir', value: 'Jammu & Kashmir'},
{id: 15, label: 'Jharkhand', value: 'Jharkhand'},
{id: 16, label: 'Karnataka', value: 'Karnataka'},
{id: 17, label: 'Kerala', value: 'Kerala'},
{id: 18, label: 'Lakshadweep', value: 'Lakshadweep'},
{id: 19, label: 'Madhya Pradesh', value: 'Madhya Pradesh'},
{id: 20, label: 'Maharashtra', value: 'Maharashtra'},
{id: 21, label: 'Manipur', value: 'Manipur'},
{id: 22, label: 'Meghalaya', value: 'Meghalaya'},
{id: 23, label: 'Mizoram', value: 'Mizoram'},
{id: 24, label: 'Nagaland', value: 'Nagaland'},
{id: 25, label: 'Orissa', value: 'Orissa'},
{id: 26, label: 'Pondicherry', value: 'Pondicherry'},
{id: 27, label: 'Punjab', value: 'Punjab'},
{id: 28, label: 'Rajasthan', value: 'Rajasthan'},
{id: 29, label: 'Sikkim', value: 'Sikkim'},
{id: 30, label: 'Tamil Nadu', value: 'Tamil Nadu'},
{id: 31, label: 'Tripura', value: 'Tripura'},
{id: 32, label: 'Uttar Pradesh', value: 'Uttar Pradesh'},
{id: 33, label: 'Uttaranchal', value: 'Uttaranchal'},
{id: 34, label: 'West Bengal', value: 'West Bengal'},

];